# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
sudo: false
python:
  - "3.4"
addons:
  apt:
    packages:
      - libatlas-base-dev
      - libatlas-dev
      - liblapack-dev
      - gfortran
      - libgmp-dev
      - libmpfr-dev
      - ccache
install: source tools/ci/install.sh
script: bash tools/ci/travis_tests.sh
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
