# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install --upgrade pip setuptools
  - pip install coverage nose six numpy scipy
  - python setup.py install
script: nosetests
