# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
sudo: false
python:
  - "3.4"
addons:
  apt:
    packages:
      - libatlas-base-dev
      - libatlas-dev
      - liblapack-dev
      - gfortran
install:
  - pip install --upgrade pip setuptools
  - travis_wait pip install -r requirements.txt
  #- pip install --upgrade coverage
  #- pip install --upgrade coveralls
  - python setup.py install
script: nosetests  # --with-coverage

# after_success:
#   - coveralls
