# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq libgmp-dev libmpfr-dev
  - mkdir builds
  - pushd builds
  # Install gmpy2 dependencies
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
  - tar xzvf mpc-1.0.2.tar.gz
  - pushd mpc-1.0.2
  - ./configure
  - make
  - sudo make install
  - popd
  # End install gmpy2 dependencies
  - pip install --upgrade pip setuptools
  - pip -v install numpy
  - pip -v install coverage
  - pip -v install coveralls
  - pip -v install nose
  - pip -v install six
  - pip -v install mpmath
  - pip -v install argparse
  - pip -v install gmpy2
  - pip -v install scipy
  - popd
install:
  - python setup.py install
script: nosetests
